// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForGameExe():Promise<string>;

export function Confirm(arg1:boolean,arg2:boolean,arg3:boolean,arg4:boolean,arg5:boolean):Promise<void>;

export function DefaultClientExePath():Promise<string>;

export function SaveGameSetup(arg1:string,arg2:string,arg3:string):Promise<void>;
