// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowseForGameExe() {
  return window['go']['main']['App']['BrowseForGameExe']();
}

export function Confirm(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['Confirm'](arg1, arg2, arg3, arg4);
}

export function DefaultClientExePath() {
  return window['go']['main']['App']['DefaultClientExePath']();
}

export function SaveGameSetup(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveGameSetup'](arg1, arg2, arg3);
}
